* <<<PE403>>> SOCIAL NETWORK ANALYSIS
:properties:
:author: Dr. V. S. Felix Enigo and Dr. G. Raghuraman
:date: 03/05/2019
:end:

#+startup: showall

** CO PO MAPPING :noexport:
10
#+NAME: co-po-mapping

|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | k2 |  2  |   2 |   1 |   1 |   1 |   0 |   0 |   1 |   0 |    1 |    0 |    0 |    3 |    1 |    1 |
| CO2            | k2 |  2  |   2 |   1 |   1 |   1 |   0 |   0 |   1 |   0 |    1 |    0 |    0 |    3 |    1 |    1 |
| CO3            | k2 |  2  |   2 |   1 |   1 |   1 |   0 |   0 |   1 |   0 |    1 |    0 |    0 |    3 |    1 |    1 |
| CO4            | K3 |  3  |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   0 |    1 |    0 |    1 |    2 |    0 |    1 |
| CO5            | K3 |  3  |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   0 |    1 |    0 |    1 |    2 |    0 |    1 |
| Score          |    |  12 |  10 |   7 |   7 |   5 |   2 |   0 |   5 |   0 |    5 |    0 |    3 |   13 |    3 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   1 |   1 |   0 |   1 |   0 |    1 |    0 |    1 |    3 |    1 |    1 |

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

#+BEGIN_COMMENT
  Course objectives changed
  Course Outcomes changed
  Text Book added
  CO-PO Mapping updated
#+END_COMMENT

** COURSE OBJECTIVES
- Understand the Fundamentals of social network analysis (SNA)
- Represent social network formally 
- Apply Community detection algorithms to Social Networks
- Apply SNA tools to work with SNA algorithms
- Make use of visualization tools to visualize Social Network 

{{{unit}}}
|UNIT I | INTRODUCTION | 9 |
Social Network Analysis: Development of social network analysis -- Key concepts and measures in network analysis -- Electronic Sources for
Network Analysis: Electronic discussion networks -- Blogs and online communities -- Web-based networks -- Social Network Data: Introduction --
Boundary specification and sampling -- Types of networks -- Network data -- Measurement and collection.

{{{unit}}}
|UNIT II | MATHEMATICAL REPRESENTATION OF SOCIAL NETWORKS | 9 |
Notations for Social Networks: Graph theoretic notations -- Sociometric notations -- Algebraic notations -- Two sets of actors -- Graph and
matrices.

{{{unit}}}
|UNIT III | COMMUNITY DETECTION METHODOLOGIES, APPLICATIONS | 9 |
Introduction -- Definition of communities -- Evaluating communities -- Methodologies of Network Community Mining: Optimization based
algorithms -- Heuristic methods -- Other methods -- Applications of community mining algorithms -- Multi-Relational characterization of
dynamic social network communities.

{{{unit}}}
|UNIT IV | PRACTICAL APPROACH TO SOCIAL NETWORK ANALYSIS | 9 |
Graph Theory: Introduction -- Adjacency matrices -- Graph Traversals and Distances -- Graph Distance; SNA Tool: Get oriented with
Python and NetworkX -- Centrality; Clique, Clusters and Components: Components and Subgraphs -- Triads -- Cliques -- Hierarchical
Clustering; 2-Mode networks; A dynamic model in Python. 


{{{unit}}}
|UNIT V | VISUALIZATION AND APPLICATIONS OF SOCIAL NETWORKS | 9 |
# Graph theory -- Centrality -- Clustering -- 
Visualizing online social networks -- Visualizing social networks with
matrix-based representations -- Node-Edge diagrams -- Matrix and
Node-Link Diagrams -- Hybrid representations; Applications: Covert
networks -- Community welfare -- Collaboration networks -- Co-citation
networks.

\hfill *Total Periods: 45*


** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Explain Social network concepts, measures and data (K2)
- Interpret social networks mathematically (K2)
- Apply various community detection algorithms to Social networks (K3)
- Apply SNA tools for analysing social networks (K3)  
- Make use of Visualization tools to social networks (K3)


** TEXTBOOKS

1. Stanley Wasserman, Katherine Faust, ``Social Network Analysis Methods and Applications'', 1st Edition, Cambridge University
   Press, 1994. (Unit I and Unit II)
2. Borko Furht, ``Handbook of Social Network Technologies and Applications'', 1st Edition, Springer, 2010. (Unit III and Unit V)

** REFERENCES

1. Peter Mika, ``Social Networks and the Semantic Web'', 1st Edition, Springer, 2007. (Unit I)
2. Maksim Tsvetovat and Alexander Kouznetsov, ``Social Network Analysis for Startups'', O’Reilly,  2011. (Unit IV)
3. Edward L. Platt, ``Network Science with Python and NetworkX Quick Start Guide: Explore and Visualize Network Data Effectively'',Packt Publishing, 2019. 
4. Stephen P Borgatti, Martin G Everett, Jeffrey G Johnson, ``Analyzing Social Networks'', SAGE Publications, 2nd Edition, 2018.
5. Charles Kadushin, ``Understanding Social Networks: Theories, Concepts, and Findings'', 1st Edition, Kindle Edition, Oxford University Press, 2012.


